lab8: lab8.o lab8s.o lab8s2.o
	gcc -Wall -g lab8s.o lab8s2.o lab8.o -o lab8

lab8s.o: lab8s.c
	gcc -Wall -g -c -O0 lab8s.c -o lab8s.o

lab8s2.o: lab8s2.s
	gcc -Wall -g -c -O0 lab8s2.s -o lab8s2.o

lab8.o: lab8.c
	gcc -Wall -g -c -O0 lab8.c -o lab8.o

